YSHERA_ARMORS = {
 --[[

    FLAG_HIDE_CHEST
    FLAG_HIDE_HEAD
    FLAG_HIDE_EYES
    FLAG_HIDE_NECK
    FLAG_HIDE_UPPERARM
    FLAG_HIDE_FOREARM
    FLAG_HIDE_HANDS
    FLAG_HIDE_TORSO
    FLAG_HIDE_THIGHS
    FLAG_HIDE_KNEES
    FLAG_HIDE_FEET

    legacy flags
    HIDE_HAIR,
    HIDE_PANTS,
    HIDE_BODY,
    HIDE_HANDS,
    HIDE_FACIAL_HAIR,
    HIDE_HAIR

    [""] = {
        ["name"] = " (C) ",
        ["model"] = "",
        ["male"] = "",
        ["female"] = "",
        ["speedboost"] = nil,
        ["BodyDR"] = nil,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 30,
        ["slot"] = "torso",
        ["flag"] = {HIDE_HEAD, HIDE_FACIAL_HAIR, HIDE_HAIR},
    },
    [""] = {
        ["name"] = " (C) ",
        ["model"] = "",
        ["male"] = "",
        ["female"] = "",
        ["speedboost"] = nil,
        ["resistanceHead"] = nil,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 30,
        ["slot"] = "helmet",
    },
    [""] = {
        ["name"] = " (C) ",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "",
        ["female"] = "",
        ["speedboost"] = 0,
        ["BodyDR"] = 65,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 1,
        ["slot"] = "torso",
        ["flag"] = {HIDE_HAIR, HIDE_PANTS, HIDE_BODY, HIDE_HANDS, HIDE_FACIAL_HAIR, HIDE_HAIR},
    }, ]]
    ["test"] = {
        ["name"] = " (C) test",
        ["model"] = "models/fallout_alaska/headgear/fullhelmet_f_bandagemask.mdl",
        ["male"] = "models/fallout_alaska/alaska_playermodels/bsharps_t30_body.mdl",
        ["female"] = "models/fallout_alaska/alaska_playermodels/bsharps_t30_body.mdl",
        ["speedboost"] = 0,
        ["HeadDR"] = 0,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 1,
        ["slot"] = "helmet",
        ["flag"] = {HIDE_FACIAL_HAIR, HIDE_HAIR},
    },
    ["test2"] = {
        ["name"] = " (C) test2",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/fallout_alaska/headgear/hat_m_boomerberet.mdl",
        ["female"] = "models/fallout_alaska/headgear/hat_f_boomerberet.mdl",
        ["speedboost"] = 0,
        ["HeadDR"] = 0,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 1,
        ["slot"] = "helmet",
        ["flag"] = {HIDE_HAIR},
    },
    ["bandage"] = {
        ["name"] = " (C) Head Bandage Mask",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/fallout_alaska/headgear/fullhelmet_m_bandagemask.mdl",
        ["female"] = "models/fallout_alaska/headgear/fullhelmet_f_bandagemask.mdl",
        ["speedboost"] = 0,
        ["HeadDR"] = 2,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 1,
        ["slot"] = "helmet",
        ["flag"] = {HIDE_HAIR, HIDE_FACIAL_HAIR},
    },
    ["clownmask"] = {
        ["name"] = " (C) Clown Mask",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/fallout_alaska/headgear/fullhelmet_f_clownmask.mdl",
        ["female"] = "models/fallout_alaska/headgear/fullhelmet_f_clownmask.mdl",
        ["speedboost"] = 0,
        ["HeadDR"] = 4,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 1,
        ["slot"] = "helmet",
        ["flag"] = {HIDE_HAIR, HIDE_FACIAL_HAIR},
    },
    ["ghoulmask"] = {
        ["name"] = " (C) Ghoul Mask",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/fallout_alaska/headgear/fullhelmet_m_ghoulmask.mdl",
        ["female"] = "models/fallout_alaska/headgear/fullhelmet_f_ghoulmask.mdl",
        ["speedboost"] = 0,
        ["HeadDR"] = 3,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 1,
        ["slot"] = "helmet",
        ["flag"] = {HIDE_HAIR, HIDE_FACIAL_HAIR},
    },
    ["lobotomitemask"] = {
        ["name"] = " (C) Lobotmite Mask",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/fallout_alaska/headgear/fullhelmet_m_lobotomite.mdl",
        ["female"] = "models/fallout_alaska/headgear/fullhelmet_f_lobotomite.mdl",
        ["speedboost"] = 0,
        ["HeadDR"] = 4,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 1,
        ["slot"] = "helmet",
        ["flag"] = {HIDE_HAIR, HIDE_FACIAL_HAIR},
    },
    ["minermask"] = {
        ["name"] = " (C) Miner Mask",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/fallout_alaska/headgear/fullhelmet_m_miner.mdl",
        ["female"] = "models/fallout_alaska/headgear/fullhelmet_f_miner.mdl",
        ["speedboost"] = 0,
        ["HeadDR"] = 4,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 1,
        ["slot"] = "helmet",
        ["flag"] = {HIDE_HAIR, HIDE_FACIAL_HAIR, FLAG_HIDE_HEAD},
    },
    ["auburntint"] = {
        ["name"] = " (C) Auburn Tint Glasses",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/fallout_alaska/headgear/glasses_m_auburntint.mdl",
        ["female"] = "models/fallout_alaska/headgear/glasses_f_auburntint.mdl",
        ["speedboost"] = 0,
        ["HeadDR"] = 2,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 1,
        ["slot"] = "glasses",
        ["flag"] = {},
    },
    ["blackrimmed"] = {
        ["name"] = " (C) Black Rimmed Glasses",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/fallout_alaska/headgear/glasses_m_blackrimmed.mdl",
        ["female"] = "models/fallout_alaska/headgear/glasses_f_blackrimmed.mdl",
        ["speedboost"] = 0,
        ["HeadDR"] = 2,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 1,
        ["slot"] = "glasses",
        ["flag"] = {},
    },
    ["blindglasses"] = {
        ["name"] = " (C) Blind Glasses",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/fallout_alaska/headgear/glasses_m_blind.mdl",
        ["female"] = "models/fallout_alaska/headgear/glasses_f_blind.mdl",
        ["speedboost"] = 0,
        ["HeadDR"] = 2,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 1,
        ["slot"] = "glasses",
        ["flag"] = {},
    },
    ["goggles"] = {
        ["name"] = " (C) Goggles",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/fallout_alaska/headgear/glasses_m_goggles.mdl",
        ["female"] = "models/fallout_alaska/headgear/glasses_f_goggles.mdl",
        ["speedboost"] = 0,
        ["HeadDR"] = 2,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 1,
        ["slot"] = "glasses",
        ["flag"] = {},
    },
    ["hearts"] = {
        ["name"] = " (C) Hearts Glasses",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/fallout_alaska/headgear/glasses_m_hearts.mdl",
        ["female"] = "models/fallout_alaska/headgear/glasses_f_hearts.mdl",
        ["speedboost"] = 0,
        ["HeadDR"] = 2,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 1,
        ["slot"] = "glasses",
        ["flag"] = {},
    },
    ["lobotomitegoggles"] = {
        ["name"] = " (C) Lobotomite Goggles",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/fallout_alaska/headgear/glasses_m_lobotomite.mdl",
        ["female"] = "models/fallout_alaska/headgear/glasses_f_lobotomite.mdl",
        ["speedboost"] = 0,
        ["HeadDR"] = 2,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 1,
        ["slot"] = "glasses",
        ["flag"] = {},
    },
    ["aviators"] = {
        ["name"] = " (C) Aviators",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/fallout_alaska/headgear/glasses_m_ncraviators.mdl",
        ["female"] = "models/fallout_alaska/headgear/glasses_f_ncraviators.mdl",
        ["speedboost"] = 0,
        ["HeadDR"] = 2,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 1,
        ["slot"] = "glasses",
        ["flag"] = {},
    },
    ["bandana"] = {
        ["name"] = " (C) Bandana",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/fallout_alaska/headgear/hat_m_bandana.mdl",
        ["female"] = "models/fallout_alaska/headgear/hat_f_bandana.mdl",
        ["speedboost"] = 0,
        ["HeadDR"] = 2,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 1,
        ["slot"] = "glasses",
        ["flag"] = {},
    },
    ["baseballcap"] = {
        ["name"] = " (C) Baseball Cap",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/fallout_alaska/headgear/hat_m_baseballcap.mdl",
        ["female"] = "models/fallout_alaska/headgear/hat_f_baseballcap.mdl",
        ["speedboost"] = 0,
        ["HeadDR"] = 2,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 1,
        ["slot"] = "helmet",
        ["flag"] = {HIDE_HAIR},
    },
    ["boomerberet"] = {
        ["name"] = " (C) Boomer Beret",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/fallout_alaska/headgear/hat_m_boomerberet.mdl",
        ["female"] = "models/fallout_alaska/headgear/hat_f_boomerberet.mdl",
        ["speedboost"] = 0,
        ["HeadDR"] = 2,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 1,
        ["slot"] = "helmet",
        ["flag"] = {HIDE_HAIR},
    },
    ["constructionhat"] = {
        ["name"] = " (C) Construction Hat",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/fallout_alaska/headgear/hat_m_constructionhat.mdl",
        ["female"] = "models/fallout_alaska/headgear/hat_f_constructionhat.mdl",
        ["speedboost"] = 0,
        ["HeadDR"] = 3,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 1,
        ["slot"] = "helmet",
        ["flag"] = {HIDE_HAIR},
    },
    ["cowboyhat"] = {
        ["name"] = " (C) Cowboy Hat",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/fallout_alaska/headgear/hat_m_cowboyhat01.mdl",
        ["female"] = "models/fallout_alaska/headgear/hat_f_cowboyhat01.mdl",
        ["speedboost"] = 0,
        ["HeadDR"] = 3,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 1,
        ["slot"] = "helmet",
        ["flag"] = {HIDE_HAIR},
    },
    ["cowboyhatblack"] = {
        ["name"] = " (C) Black Cowboy Hat",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/fallout_alaska/headgear/hat_m_cowboyhat03.mdl",
        ["female"] = "models/fallout_alaska/headgear/hat_f_cowboyhat03.mdl",
        ["speedboost"] = 0,
        ["HeadDR"] = 3,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 1,
        ["slot"] = "helmet",
        ["flag"] = {HIDE_HAIR},
    },
    ["druidhood"] = {
        ["name"] = " (C) Druid Hood",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/fallout_alaska/headgear/hat_m_druidhood.mdl",
        ["female"] = "models/fallout_alaska/headgear/hat_f_druidhood.mdl",
        ["speedboost"] = 0,
        ["HeadDR"] = 3,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 1,
        ["slot"] = "helmet",
        ["flag"] = {HIDE_HAIR},
    },
    ["fedora"] = {
        ["name"] = " (C) Fedora Hat",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/fallout_alaska/headgear/hat_m_fedora.mdl",
        ["female"] = "models/fallout_alaska/headgear/hat_f_fedora.mdl",
        ["speedboost"] = 0,
        ["HeadDR"] = 3,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 1,
        ["slot"] = "helmet",
        ["flag"] = {HIDE_HAIR},
    },
    ["fedorablackrimmed"] = {
        ["name"] = " (C) Black Fedora Hat",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/fallout_alaska/headgear/hat_f_fedora2.mdl",
        ["female"] = "models/fallout_alaska/headgear/hat_f_fedora2.mdl",
        ["speedboost"] = 0,
        ["HeadDR"] = 3,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 1,
        ["slot"] = "helmet",
        ["flag"] = {HIDE_HAIR},
    },
    ["firehelmet"] = {
        ["name"] = " (C) Fire Helmet",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/fallout_alaska/headgear/hat_m_firehelmet.mdl",
        ["female"] = "models/fallout_alaska/headgear/hat_f_firehelmet.mdl",
        ["speedboost"] = 0,
        ["HeadDR"] = 3,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 1,
        ["slot"] = "helmet",
        ["flag"] = {HIDE_HAIR},
    },
    ["merchanthat"] = {
        ["name"] = " (C) Merchant Hat",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/fallout_alaska/headgear/hat_m_merchanthat.mdl",
        ["female"] = "models/fallout_alaska/headgear/hat_f_merchanthat.mdl",
        ["speedboost"] = 0,
        ["HeadDR"] = 3,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 1,
        ["slot"] = "helmet",
        ["flag"] = {HIDE_HAIR},
    },
    ["motorcyclehelmet"] = {
        ["name"] = " (C) Motorcycle Helmet",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/fallout_alaska/headgear/hat_m_motorcyclehelmet.mdl",
        ["female"] = "models/fallout_alaska/headgear/hat_f_motorcyclehelmet.mdl",
        ["speedboost"] = 0,
        ["HeadDR"] = 3,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 1,
        ["slot"] = "helmet",
        ["flag"] = {HIDE_HAIR},
    },
    ["partyhat"] = {
        ["name"] = " (C) Party Hat",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/fallout_alaska/headgear/hat_m_partyhat01.mdl",
        ["female"] = "models/fallout_alaska/headgear/hat_f_partyhat01.mdl",
        ["speedboost"] = 0,
        ["HeadDR"] = 3,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 1,
        ["slot"] = "helmet",
        ["flag"] = {},
    },
    ["pimphat"] = {
        ["name"] = " (C) Pimp Hat",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/fallout_alaska/headgear/hat_m_pimphat.mdl",
        ["female"] = "models/fallout_alaska/headgear/hat_f_pimphat.mdl",
        ["speedboost"] = 0,
        ["HeadDR"] = 3,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 1,
        ["slot"] = "helmet",
        ["flag"] = {HIDE_HAIR},
    },
    ["rangerhat"] = {
        ["name"] = " (C) Ranger Hat",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/fallout_alaska/headgear/hat_m_rangerhat.mdl",
        ["female"] = "models/fallout_alaska/headgear/hat_f_rangerhat.mdl",
        ["speedboost"] = 0,
        ["HeadDR"] = 4,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 1,
        ["slot"] = "helmet",
        ["flag"] = {HIDE_HAIR},
    },
    ["slavehood"] = {
        ["name"] = " (C) Slave Hood",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/fallout_alaska/headgear/hat_m_slave01.mdl",
        ["female"] = "models/fallout_alaska/headgear/hat_f_slave01.mdl",
        ["speedboost"] = 0,
        ["HeadDR"] = 2,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 1,
        ["slot"] = "helmet",
        ["flag"] = {HIDE_HAIR},
    },
    ["slaverag"] = {
        ["name"] = " (C) Slave Rag",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/fallout_alaska/headgear/hat_m_slave02.mdl",
        ["female"] = "models/fallout_alaska/headgear/hat_f_slave02.mdl",
        ["speedboost"] = 0,
        ["HeadDR"] = 2,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 1,
        ["slot"] = "helmet",
        ["flag"] = {HIDE_HAIR},
    },
    ["tophat"] = {
        ["name"] = " (C) Top Hat",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/fallout_alaska/headgear/hat_m_tophat.mdl",
        ["female"] = "models/fallout_alaska/headgear/hat_f_tophat.mdl",
        ["speedboost"] = 0,
        ["HeadDR"] = 3,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 1,
        ["slot"] = "helmet",
        ["flag"] = {HIDE_HAIR},
    },
    ["wastelandclothinghood"] = {
        ["name"] = " (C) Wastelander Hood",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/fallout_alaska/headgear/hat_m_wastelandclothinghood.mdl",
        ["female"] = "models/fallout_alaska/headgear/hat_f_wastelandclothinghood.mdl",
        ["speedboost"] = 0,
        ["HeadDR"] = 3,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 1,
        ["slot"] = "helmet",
        ["flag"] = {HIDE_HAIR},
    },
    ["boomerhat"] = {
        ["name"] = " (C) Boomer Hat",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/fallout_alaska/headgear/helmet_m_boomerhat.mdl",
        ["female"] = "models/fallout_alaska/headgear/helmet_f_boomerhat.mdl",
        ["speedboost"] = 0,
        ["HeadDR"] = 3,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 1,
        ["slot"] = "helmet",
        ["flag"] = {HIDE_HAIR},
    },
    ["combatarmorhelmet"] = {
        ["name"] = " (C) Combat Armor Helmet",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/fallout_alaska/headgear/helmet_m_combatarmor01.mdl",
        ["female"] = "models/fallout_alaska/headgear/helmet_f_combatarmor01.mdl",
        ["speedboost"] = 0,
        ["HeadDR"] = 5,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 1,
        ["slot"] = "helmet",
        ["flag"] = {HIDE_HAIR},
    },
    ["eyebothelmet"] = {
        ["name"] = " (C) Eyebot Helmet",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/fallout_alaska/headgear/helmet_m_eyebot.mdl",
        ["female"] = "models/fallout_alaska/headgear/helmet_f_eyebot.mdl",
        ["speedboost"] = 0,
        ["HeadDR"] = 4,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 1,
        ["slot"] = "helmet",
        ["flag"] = {HIDE_HAIR},
    },
    ["fiendhelmet"] = {
        ["name"] = " (C) Fiend Helmet",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/fallout_alaska/headgear/helmet_m_fiend.mdl",
        ["female"] = "models/fallout_alaska/headgear/helmet_f_fiend.mdl",
        ["speedboost"] = 0,
        ["HeadDR"] = 5,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 1,
        ["slot"] = "helmet",
        ["flag"] = {HIDE_HAIR},
    },
    ["metalarmorhelmet"] = {
        ["name"] = " (C) Metal Helmet",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/fallout_alaska/headgear/helmet_m_metalarmor.mdl",
        ["female"] = "models/fallout_alaska/headgear/helmet_f_metalarmor.mdl",
        ["speedboost"] = 0,
        ["HeadDR"] = 6,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 1,
        ["slot"] = "helmet",
        ["flag"] = {HIDE_HAIR},
    },
    ["raiderhat"] = {
        ["name"] = " (C) Raider Hat",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/fallout_alaska/headgear/helmet_m_raiderhat02.mdl",
        ["female"] = "models/fallout_alaska/headgear/helmet_f_raiderhat02.mdl",
        ["speedboost"] = 0,
        ["HeadDR"] = 6,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 1,
        ["slot"] = "helmet",
        ["flag"] = {HIDE_HAIR},
    },
    ["raiderhood"] = {
        ["name"] = " (C) Raider Hood",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/fallout_alaska/headgear/helmet_m_raiderhood.mdl",
        ["female"] = "models/fallout_alaska/headgear/helmet_f_raiderhood.mdl",
        ["speedboost"] = 0,
        ["HeadDR"] = 5,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 1,
        ["slot"] = "helmet",
        ["flag"] = {HIDE_HAIR},
    },
    ["securityhelmet"] = {
        ["name"] = " (C) Security Helmet",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/fallout_alaska/headgear/helmet_m_securityhelmet.mdl",
        ["female"] = "models/fallout_alaska/headgear/helmet_f_securityhelmet.mdl",
        ["speedboost"] = 0,
        ["HeadDR"] = 5,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 1,
        ["slot"] = "helmet",
        ["flag"] = {HIDE_HAIR},
    },
    ["beretgreen"] = {
        ["name"] = " (C) Green Beret",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/fallout_alaska/headgear_other/alaska/hat_beretgreen.mdl",
        ["female"] = "models/fallout_alaska/headgear_other/alaska/hat_beretgreen.mdl",
        ["speedboost"] = 0,
        ["HeadDR"] = 7,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 1,
        ["slot"] = "helmet",
        ["flag"] = {HIDE_HAIR},
    },
    ["beretred"] = {
        ["name"] = " (C) Red Beret",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/fallout_alaska/headgear_other/alaska/hat_beretred.mdl",
        ["female"] = "models/fallout_alaska/headgear_other/alaska/hat_beretred.mdl",
        ["speedboost"] = 0,
        ["HeadDR"] = 7,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 1,
        ["slot"] = "helmet",
        ["flag"] = {HIDE_HAIR},
    },
    ["bonnet"] = {
        ["name"] = " (C) Bonnet",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/fallout_alaska/headgear_other/alaska/hat_bonnet.mdl",
        ["female"] = "models/fallout_alaska/headgear_other/alaska/hat_bonnet.mdl",
        ["speedboost"] = 0,
        ["HeadDR"] = 3,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 1,
        ["slot"] = "helmet",
        ["flag"] = {HIDE_HAIR},
    },
    ["fedora2"] = {
        ["name"] = " (C) Fedora Hat",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/fallout_alaska/headgear_other/alaska/hat_fedora.mdl",
        ["female"] = "models/fallout_alaska/headgear_other/alaska/hat_fedora.mdl",
        ["speedboost"] = 0,
        ["HeadDR"] = 3,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 1,
        ["slot"] = "helmet",
        ["flag"] = {HIDE_HAIR},
    },
    ["mexicanhat"] = {
        ["name"] = " (C) Mexican Hat",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/fallout_alaska/headgear_other/alaska/hat_mexican.mdl",
        ["female"] = "models/fallout_alaska/headgear_other/alaska/hat_mexican.mdl",
        ["speedboost"] = 0,
        ["HeadDR"] = 3,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 1,
        ["slot"] = "helmet",
        ["flag"] = {HIDE_HAIR},
    },
    ["tanrangerhat"] = {
        ["name"] = " (C) Tan Ranger Hat",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/fallout_alaska/headgear_other/alaska/hat_ranger.mdl",
        ["female"] = "models/fallout_alaska/headgear_other/alaska/hat_ranger.mdl",
        ["speedboost"] = 0,
        ["HeadDR"] = 3,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 1,
        ["slot"] = "helmet",
        ["flag"] = {HIDE_HAIR},
    },
    ["trooperhelm"] = {
        ["name"] = " (C) Trooper Helm",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/fallout_alaska/headgear_other/alaska/hat_trooper.mdl",
        ["female"] = "models/fallout_alaska/headgear_other/alaska/hat_trooper.mdl",
        ["speedboost"] = 0,
        ["HeadDR"] = 6,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 1,
        ["slot"] = "helmet",
        ["flag"] = {HIDE_HAIR},
    },
    ["troopermphat"] = {
        ["name"] = " (C) Trooper Military Police Hat",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/fallout_alaska/headgear_other/alaska/hat_trooper_mp.mdl",
        ["female"] = "models/fallout_alaska/headgear_other/alaska/hat_trooper_mp.mdl",
        ["speedboost"] = 0,
        ["HeadDR"] = 6,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 1,
        ["slot"] = "helmet",
        ["flag"] = {HIDE_HAIR},
    },
    ["trooperglasseshat"] = {
        ["name"] = " (C) Trooper Hat W/ Glasses",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/fallout_alaska/headgear_other/alaska/helmet_trooperglasses.mdl",
        ["female"] = "models/fallout_alaska/headgear_other/alaska/helmet_trooperglasses.mdl",
        ["speedboost"] = 0,
        ["HeadDR"] = 6,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 1,
        ["slot"] = "helmet",
        ["flag"] = {HIDE_HAIR},
    },
    ["troopermpglasseshat"] = {
        ["name"] = " (C) Trooper Military Police Hat W/ Glasses",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/fallout_alaska/headgear_other/alaska/helmet_trooperglasses_mp.mdl",
        ["female"] = "models/fallout_alaska/headgear_other/alaska/helmet_trooperglasses_mp.mdl",
        ["speedboost"] = 0,
        ["HeadDR"] = 6,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 1,
        ["slot"] = "helmet",
        ["flag"] = {HIDE_HAIR},
    },
    ["breather"] = {
        ["name"] = " (C) Breather",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/fallout_alaska/headgear/mask_m_breather.mdl",
        ["female"] = "models/fallout_alaska/headgear/mask_f_breather.mdl",
        ["speedboost"] = 0,
        ["HeadDR"] = 4,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 1,
        ["slot"] = "helmet",
        ["flag"] = {},
    },
    ["surgicalmask"] = {
        ["name"] = " (C) Surgical Mask",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/fallout_alaska/headgear/mask_m_surgicalmask.mdl",
        ["female"] = "models/fallout_alaska/headgear/mask_f_surgicalmask.mdl",
        ["speedboost"] = 0,
        ["HeadDR"] = 3,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 1,
        ["slot"] = "helmet",
        ["flag"] = {HIDE_FACIAL_HAIR},
    },
    ["weldingmask"] = {
        ["name"] = " (C) Welding Mask",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/fallout_alaska/headgear/mask_m_weldingmask.mdl",
        ["female"] = "models/fallout_alaska/headgear/mask_f_weldingmask.mdl",
        ["speedboost"] = 0,
        ["HeadDR"] = 5,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 1,
        ["slot"] = "helmet",
        ["flag"] = {HIDE_HAIR},
    },
    ["whitemask"] = {
        ["name"] = " (C) White Mask",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/fallout_alaska/headgear/mask_m_whitemask.mdl",
        ["female"] = "models/fallout_alaska/headgear/mask_f_whitemask.mdl",
        ["speedboost"] = 0,
        ["HeadDR"] = 3,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 1,
        ["slot"] = "helmet",
        ["flag"] = {},
    },
    ["trooperhat"] = {
        ["name"] = " (C) Trooper Hat",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/thespireroleplay/humans/headgear/ncrhats_m.mdl",
        ["female"] = "models/thespireroleplay/humans/headgear/ncrhats_f.mdl",
        ["speedboost"] = 0,
        ["HeadDR"] = 6,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 1,
        ["slot"] = "helmet",
        ["flag"] = {},
    },
    ["mantle"] = {
        ["name"] = " (C) Mantle",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/thespireroleplay/humans/gear/mantle_m.mdl",
        ["female"] = "models/thespireroleplay/humans/gear/mantle_m.mdl",
        ["speedboost"] = 0,
        ["HeadDR"] = 0,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 1,
        ["slot"] = "extra",
        ["flag"] = {},
    },
    ["leatherarmorpieces"] = {
        ["name"] = " (C) Leather Armor Pieces",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/thespireroleplay/humans/gear/male_armor.mdl",
        ["female"] = "models/thespireroleplay/humans/gear/female_armor.mdl",
        ["speedboost"] = 0,
        ["HeadDR"] = 0,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 1,
        ["slot"] = "extra1",
        ["flag"] = {},
    },
    ["binnoc"] = {
        ["name"] = " (C) Binoculars",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/thespireroleplay/humans/gear/binoc_m.mdl",
        ["female"] = "models/thespireroleplay/humans/gear/binoc_m.mdl",
        ["speedboost"] = 0,
        ["HeadDR"] = 0,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 1,
        ["slot"] = "extra2",
        ["flag"] = {},
    },
    ["satchel"] = {
        ["name"] = " (C) Satchel",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/thespireroleplay/humans/gear/satchel_m.mdl",
        ["female"] = "models/thespireroleplay/humans/gear/satchel_m.mdl",
        ["speedboost"] = 0,
        ["HeadDR"] = 0,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 1,
        ["slot"] = "extra3",
        ["flag"] = {},
    },
    ["flamethrowerpack"] = {
        ["name"] = " (C) Flamethrower Pack",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/thespireroleplay/humans/gear/backpack_m.mdl",
        ["female"] = "models/thespireroleplay/humans/gear/backpack_f.mdl",
        ["speedboost"] = 0,
        ["HeadDR"] = 0,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 1,
        ["slot"] = "extra4",
        ["flag"] = {},
    },
    --armors {HIDE_PANTS, HIDE_HANDS, HIDE_FACIAL_HAIR, HIDE_HAIR, HIDE_BODY, HIDE_TORSO}
    ["rags"] = {
        ["name"] = " (C) Rags",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/thespireroleplay/humans/group015/male.mdl",
        ["female"] = "models/thespireroleplay/humans/group015/female.mdl",
        ["speedboost"] = 0,
        ["BodyDR"] = 25,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 2,
        ["slot"] = "torso",
        ["flag"] = {HIDE_PANTS, HIDE_BODY},
    },
    ["MerchantOutfit"] = {
        ["name"] = " (C) Merchant Outfit",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/thespireroleplay/humans/group104/male.mdl",
        ["female"] = "models/thespireroleplay/humans/group104/female.mdl",
        ["speedboost"] = 0,
        ["BodyDR"] = 32,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 4,
        ["slot"] = "torso",
        ["flag"] = {HIDE_PANTS, HIDE_BODY},
    },
    ["robe"] = {
        ["name"] = " (C) Waster Scribe",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/thespireroleplay/humans/group201/male.mdl",
        ["female"] = "models/thespireroleplay/humans/group201/female.mdl",
        ["speedboost"] = 0,
        ["BodyDR"] = 30,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 4,
        ["slot"] = "torso",
        ["flag"] = {HIDE_PANTS, HIDE_BODY},
    },
    ["casualOutfit"] = {
        ["name"] = " (C) Casual Outfit",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/thespireroleplay/humans/group103/male.mdl",
        ["female"] = "models/thespireroleplay/humans/group103/female.mdl",
        ["speedboost"] = 0,
        ["BodyDR"] = 28,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 4,
        ["slot"] = "torso",
        ["flag"] = {HIDE_PANTS},
    },
    ["GreenJumpsuit"] = {
        ["name"] = " (C) Green Jumpsuit",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/thespireroleplay/humans/group006/male.mdl",
        ["female"] = "models/thespireroleplay/humans/group006/female.mdl",
        ["speedboost"] = 0,
        ["BodyDR"] = 23,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 4,
        ["slot"] = "torso",
        ["flag"] = {HIDE_PANTS, FLAG_HIDE_TORSO, FLAG_HIDE_UPPERARM, FLAG_HIDE_CHEST},
    },
    ["WhiteJumpsuit"] = {
        ["name"] = " (C) White Jumpsuit",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/thespireroleplay/humans/group007/male.mdl",
        ["female"] = "models/thespireroleplay/humans/group007/female.mdl",
        ["speedboost"] = 0,
        ["BodyDR"] = 20,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 4,
        ["slot"] = "torso",
        ["flag"] = {HIDE_PANTS, HIDE_BODY},
    },
    ["VaultJumpsuit"] = {
        ["name"] = " (C) Vault Jumpsuit",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/thespireroleplay/humans/group010/male.mdl",
        ["female"] = "models/thespireroleplay/humans/group010/female.mdl",
        ["speedboost"] = 0,
        ["BodyDR"] = 25,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 4,
        ["slot"] = "torso",
        ["flag"] = {HIDE_PANTS, HIDE_BODY},
    },
    ["metalarmor"] = {
        ["name"] = " (C) Metal Armor",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/thespireroleplay/humans/group011/male.mdl",
        ["female"] = "models/thespireroleplay/humans/group011/female.mdl",
        ["speedboost"] = 0,
        ["BodyDR"] = 40,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 10,
        ["slot"] = "torso",
        ["flag"] = {HIDE_PANTS, HIDE_BODY},
    },
    ["raiderarmor"] = {
        ["name"] = " (C) Raider Armor",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/thespireroleplay/humans/group133/male.mdl",
        ["female"] = "models/thespireroleplay/humans/group133/female.mdl",
        ["speedboost"] = 2,
        ["BodyDR"] = 40,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 22,
        ["slot"] = "torso",
        ["flag"] = {FLAG_HIDE_FEET, FLAG_HIDE_THIGHS},
    },
    ["raiderarmor2"] = {
        ["name"] = " (C) Heavy Raider Armor",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/thespireroleplay/humans/group316/male.mdl",
        ["female"] = "models/thespireroleplay/humans/group316/female.mdl",
        ["speedboost"] = 3,
        ["BodyDR"] = 43,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 12,
        ["slot"] = "torso",
        ["flag"] = {HIDE_PANTS},
    },
    ["raiderarmor3"] = {
        ["name"] = " (C) Light Raider Armor",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/thespireroleplay/humans/group507/male.mdl",
        ["female"] = "models/thespireroleplay/humans/group507/female.mdl",
        ["speedboost"] = 0,
        ["BodyDR"] = 35,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 6,
        ["slot"] = "torso",
        ["flag"] = {FLAG_HIDE_FEET, FLAG_HIDE_THIGHS},
    },
    ["GreenCombatarmor"] = {
        ["name"] = " (C) Green Combat Armor",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/thespireroleplay/humans/group012/male.mdl",
        ["female"] = "models/thespireroleplay/humans/group012/female.mdl",
        ["speedboost"] = 0,
        ["BodyDR"] = 24,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 12,
        ["slot"] = "torso",
        ["flag"] = {HIDE_PANTS},
    },
    ["CasualAttire"] = {
        ["name"] = " (C) Casual Attire",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/thespireroleplay/humans/group013/male.mdl",
        ["female"] = "models/thespireroleplay/humans/group013/male.mdl",
        ["speedboost"] = 0,
        ["BodyDR"] = 10,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 4,
        ["slot"] = "torso",
        ["flag"] = {HIDE_PANTS, HIDE_BODY},
    },
    ["SuitAttire"] = {
        ["name"] = " (C) Suit Attire",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/thespireroleplay/humans/group014/male.mdl",
        ["female"] = "models/thespireroleplay/humans/group014/male.mdl",
        ["speedboost"] = 0,
        ["BodyDR"] = 10,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 4,
        ["slot"] = "torso",
        ["flag"] = {HIDE_PANTS, HIDE_BODY},
    },
    ["brownragsoutfit"] = {
        ["name"] = " (C) Brown Rags Outfit",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/thespireroleplay/humans/group0/male.mdl",
        ["female"] = "models/thespireroleplay/humans/group0/female.mdl",
        ["speedboost"] = 0,
        ["BodyDR"] = 5,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 2,
        ["slot"] = "torso",
        ["flag"] = {HIDE_PANTS, HIDE_BODY},
    },
    ["lobotomiteoutfit"] = {
        ["name"] = " (C) Lobotomite Outfit",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/thespireroleplay/humans/group019/group018/male.mdl",
        ["female"] = "models/thespireroleplay/humans/group019/group018/male.mdl",
        ["speedboost"] = 0,
        ["BodyDR"] = 20,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 4,
        ["slot"] = "torso",
        ["flag"] = {HIDE_PANTS, HIDE_BODY},
    },
    ["PrewarWhiteSuit"] = {
        ["name"] = " (C) Pre-war White Suit",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/thespireroleplay/humans/group027/male.mdl",
        ["female"] = "models/thespireroleplay/humans/group027/male.mdl",
        ["speedboost"] = 0,
        ["BodyDR"] = 10,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 4,
        ["slot"] = "torso",
        ["flag"] = {HIDE_PANTS, HIDE_BODY},
    },
    ["furcoat"] = {
        ["name"] = " (C) Fur Coat",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/player/coat.mdl",
        ["female"] = "models/player/coat.mdl",
        ["speedboost"] = 0,
        ["BodyDR"] = 0,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 3,
        ["slot"] = "coat",
        ["flag"] = {},
    },
    ["leathercoat"] = {
        ["name"] = " (C) Ranger Coat",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/visualitygaming/fallout/prop/rangercoat_male.mdl",
        ["female"] = "models/visualitygaming/fallout/prop/rangercoat_female.mdl",
        ["speedboost"] = 0,
        ["BodyDR"] = 0,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 8,
        ["slot"] = "coat",
        ["flag"] = {},
    },
    ["Alaskancolonelcoat"] = {
        ["name"] = " (C) Alaskan Colonel Coat",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/ncr/colonelm.mdl",
        ["female"] = "models/ncr/colonelf.mdl",
        ["speedboost"] = 15,
        ["BodyDR"] = 65,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 1,
        ["slot"] = "torso",
        ["flag"] = {HIDE_PANTS, HIDE_BODY},
    },
    ["exileduniform"] = {
        ["name"] = " (C) Exiled Uniform",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/ncr/exilef.mdl",
        ["female"] = "models/ncr/exilef.mdl",
        ["speedboost"] = 0,
        ["BodyDR"] = 40,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 1,
        ["slot"] = "torso",
        ["flag"] = {HIDE_PANTS, HIDE_BODY},
    },
    ["apatesla"] = {
        ["name"] = " (C) Tesla Advanced Power Armor",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/fallout_alaska/alaska_playermodels/apatesla1_body.mdl",
        ["female"] = "models/fallout_alaska/alaska_playermodels/apatesla1_body.mdl",
        ["speedboost"] = 0,
        ["BodyDR"] = 65,
        ["training"] = true,
        ["price"] = 0,
        ["weight"] = 25,
        ["slot"] = "torso",
        ["flag"] = {HIDE_PANTS, HIDE_BODY, HIDE_HANDS},
    },
    ["apateslahelmet"] = {
        ["name"] = " (C) Tesla Advanced Power Armor Helmet",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/fallout_alaska/alaska_playermodels/apatesla1_helmet.mdl",
        ["female"] = "models/fallout_alaska/alaska_playermodels/apatesla1_helmet.mdl",
        ["speedboost"] = 0,
        ["HeadDR"] = 10,
        ["training"] = true,
        ["price"] = 0,
        ["weight"] = 10,
        ["slot"] = "helmet",
        ["flag"] = {HIDE_FACIAL_HAIR, HIDE_HAIR, FLAG_HIDE_HEAD},
    },
    ["AlaskanKingsOutfit"] = {
        ["name"] = " (C) Alaskan Kings Outfit",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/thespireroleplay/humans/group0301/male.mdl",
        ["female"] = "models/thespireroleplay/humans/group0301/female.mdl",
        ["speedboost"] = 0,
        ["BodyDR"] = 11,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 1,
        ["slot"] = "torso",
        ["flag"] = {HIDE_PANTS, HIDE_BODY},
    },
    ["Leathergear"] = {
        ["name"] = " (C) Leather Gear",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/thespireroleplay/humans/group052/male.mdl",
        ["female"] = "models/thespireroleplay/humans/group052/female.mdl",
        ["speedboost"] = 0,
        ["BodyDR"] = 25,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 7,
        ["slot"] = "torso",
        ["flag"] = {HIDE_PANTS, HIDE_BODY},
    },
    ["Greencombatgear"] = {
        ["name"] = " (C) Green Combat Gear",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/thespireroleplay/humans/group0303/male.mdl",
        ["female"] = "models/thespireroleplay/humans/group0303/female.mdl",
        ["speedboost"] = 0,
        ["BodyDR"] = 28,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 12,
        ["slot"] = "torso",
        ["flag"] = {HIDE_PANTS, HIDE_BODY},
    },
    ["tancombatgear"] = {
        ["name"] = " (C) Tan Combat Gear",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/thespireroleplay/humans/group024/male.mdl",
        ["female"] = "models/thespireroleplay/humans/group024/female.mdl",
        ["speedboost"] = 0,
        ["BodyDR"] = 28,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 12,
        ["slot"] = "torso",
        ["flag"] = {HIDE_PANTS, HIDE_BODY},
    },
    ["MercenaryOutfit"] = {
        ["name"] = " (C) Mercenary Outfit",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/thespireroleplay/humans/group061/male.mdl",
        ["female"] = "models/thespireroleplay/humans/group061/female.mdl",
        ["speedboost"] = 2,
        ["BodyDR"] = 25,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 1,
        ["slot"] = "torso",
        ["flag"] = {HIDE_PANTS, HIDE_BODY},
    },
    ["MakeshiftMetalCombatArmor"] = {
        ["name"] = " (C) Makeshift Leather Combat Armor",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/thespireroleplay/humans/group016/male.mdl",
        ["female"] = "models/thespireroleplay/humans/group016/female.mdl",
        ["speedboost"] = 0,
        ["BodyDR"] = 35,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 13,
        ["slot"] = "torso",
        ["flag"] = {HIDE_PANTS, FLAG_HIDE_TORSO},
    },
    ["ExiledRangerTraineeArmor"] = {
        ["name"] = " (C) Exiled Ranger Trainee Armor",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/thespireroleplay/humans/group016/male.mdl",
        ["female"] = "models/thespireroleplay/humans/group016/female.mdl",
        ["speedboost"] = 0,
        ["BodyDR"] = 43,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 13,
        ["slot"] = "torso",
        ["flag"] = {HIDE_PANTS, HIDE_BODY},
    },
    ["MercenaryArmor"] = {
        ["name"] = " (C) Mercenary Armor",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/thespireroleplay/humans/group021/male.mdl",
        ["female"] = "models/thespireroleplay/humans/group021/female.mdl",
        ["speedboost"] = 3,
        ["BodyDR"] = 30,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 6,
        ["slot"] = "torso",
        ["flag"] = {HIDE_PANTS, HIDE_BODY},
    },
    ["CowboyCasual"] = {
        ["name"] = " (C) Cowboy Casual",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/thespireroleplay/humans/group003/male.mdl",
        ["female"] = "models/thespireroleplay/humans/group003/female.mdl",
        ["speedboost"] = 2,
        ["BodyDR"] = 20,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 5,
        ["slot"] = "torso",
        ["flag"] = {HIDE_PANTS, HIDE_BODY},
    },
    ["thinktankstealthsuit"] = {
        ["name"] = " (C) think tank stealth suit",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/thespireroleplay/humans/group005/male.mdl",
        ["female"] = "models/thespireroleplay/humans/group005/female.mdl",
        ["speedboost"] = 4,
        ["BodyDR"] = 30,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 1,
        ["slot"] = "torso",
        ["flag"] = {HIDE_PANTS, HIDE_BODY},
    },
    ["RangerCasuals"] = {
        ["name"] = " (C) Ranger Casuals",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/thespireroleplay/humans/group058/male.mdl",
        ["female"] = "models/thespireroleplay/humans/group058/female.mdl",
        ["speedboost"] = 3,
        ["BodyDR"] = 43,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 1,
        ["slot"] = "torso",
        ["flag"] = {HIDE_PANTS, HIDE_BODY},
    },
    ["Lonecourier"] = {
        ["name"] = " (C) Lone Courier",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/thespireroleplay/humans/group514/male.mdl",
        ["female"] = "models/thespireroleplay/humans/group514/female.mdl",
        ["speedboost"] = 0,
        ["BodyDR"] = 65,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 1,
        ["slot"] = "torso",
        ["flag"] = {HIDE_PANTS, FLAG_HIDE_CHEST, FLAG_HIDE_TORSO},
    },
    --enclave
    ["EnclaveEnlisted"] = {
        ["name"] = " (C) Enclave Enlisted",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/thespireroleplay/humans/group113/male.mdl",
        ["female"] = "models/thespireroleplay/humans/group113/female.mdl",
        ["speedboost"] = 3,
        ["BodyDR"] = 40,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 5,
        ["slot"] = "torso",
        ["flag"] = {HIDE_PANTS, HIDE_BODY},
    },
    ["EnclaveTrooperUniform"] = {
        ["name"] = " (C) Enclave Trooper Uniform",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/thespireroleplay/humans/group199/male.mdl",
        ["female"] = "models/thespireroleplay/humans/group199/female.mdl",
        ["speedboost"] = 2,
        ["BodyDR"] = 42,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 6,
        ["slot"] = "torso",
        ["flag"] = {HIDE_PANTS, HIDE_BODY, HIDE_HANDS},
    },
    ["Enclavehat"] = {
        ["name"] = " (C) Enclave Hat",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/fallout_alaska/playermodels/enclave_officer/enclaveofficer_male_hat.mdl",
        ["female"] = "models/fallout_alaska/playermodels/enclave_officer/enclaveofficer_female_hat.mdl",
        ["speedboost"] = 0,
        ["HeadDR"] = 6,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 1,
        ["slot"] = "helmet",
        ["flag"] = {HIDE_HAIR},
    },
    ["Enclavecolonelpa"] = {
        ["name"] = " (C) Enclave Colonel PA",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/ncr/enclavepa.mdl",
        ["female"] = "models/ncr/enclavepa.mdl",
        ["speedboost"] = -6,
        ["BodyDR"] = 65,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 1,
        ["slot"] = "torso",
        ["flag"] = {HIDE_PANTS, HIDE_BODY},
    },
    ["enclavecolonelpowerarmorhelmet"] = {
        ["name"] = " (C) Enclave Colonel Power Armor Helmet",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/ncr/enclavehelm.mdl",
        ["female"] = "models/ncr/enclavehelm.mdl",
        ["speedboost"] = 0,
        ["HeadDR"] = 10,
        ["training"] = true,
        ["price"] = 0,
        ["weight"] = 1,
        ["slot"] = "helmet",
        ["flag"] = {HIDE_FACIAL_HAIR, HIDE_HAIR, FLAG_HIDE_HEAD},
    },
    ["enclavepowerarmor"] = {
        ["name"] = " (C) Enclave Power Armor",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/fallout_alaska/alaska_playermodels/enclave_power_armor_body.mdl",
        ["female"] = "models/fallout_alaska/alaska_playermodels/enclave_power_armor_body.mdl",
        ["speedboost"] = -5,
        ["BodyDR"] = 55,
        ["training"] = true,
        ["price"] = 0,
        ["weight"] = 1,
        ["slot"] = "torso",
        ["flag"] = {HIDE_PANTS, HIDE_BODY, HIDE_HANDS, HIDE_FACIAL_HAIR, HIDE_HAIR},
    },
    ["enclavepowerarmorhelmet"] = {
        ["name"] = " (C) Enclave Power Armor Helmet",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/fallout_alaska/alaska_playermodels/enclave_power_armor_helmet.mdl",
        ["female"] = "models/fallout_alaska/alaska_playermodels/enclave_power_armor_helmet.mdl",
        ["speedboost"] = 0,
        ["HeadDR"] = 8,
        ["training"] = true,
        ["price"] = 0,
        ["weight"] = 1,
        ["slot"] = "helmet",
        ["flag"] = {HIDE_FACIAL_HAIR, HIDE_HAIR, FLAG_HIDE_HEAD},
    },
    ["enclaveteslapowerarmor"] = {
        ["name"] = " (C) Enclave Tesla Power Armor",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/fallout_3/tesla_power_armor_body.mdl",
        ["female"] = "models/fallout_3/tesla_power_armor_body.mdl",
        ["speedboost"] = 0,
        ["BodyDR"] = 65,
        ["training"] = true,
        ["price"] = 0,
        ["weight"] = 1,
        ["slot"] = "torso",
        ["flag"] = {HIDE_PANTS, HIDE_BODY, HIDE_HANDS},
    },
    ["enclaveteslapowerarmorhelmet"] = {
        ["name"] = " (C) Enclave Tesla Power Armor Helmet",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/fallout_3/tesla_power_armor_helmet.mdl",
        ["female"] = "models/fallout_3/tesla_power_armor_helmet.mdl",
        ["speedboost"] = -5,
        ["HeadDR"] = 10,
        ["training"] = true,
        ["price"] = 0,
        ["weight"] = 1,
        ["slot"] = "helmet",
        ["flag"] = {HIDE_FACIAL_HAIR, HIDE_HAIR, FLAG_HIDE_HEAD},
    },
    ["enclaveHellfirepowerarmor"] = {
        ["name"] = " (C) Enclave Hellfire Power Armor ",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/fallout_alaska/alaska_playermodels/enclave_colonel_body.mdl",
        ["female"] = "models/fallout_alaska/alaska_playermodels/enclave_colonel_body.mdl",
        ["speedboost"] = -5,
        ["BodyDR"] = 50,
        ["training"] = true,
        ["price"] = 0,
        ["weight"] = 1,
        ["slot"] = "torso",
        ["flag"] = {HIDE_PANTS, HIDE_BODY, HIDE_HANDS},
    },
    ["enclaveHellfirepowerarmorhelmet"] = {
        ["name"] = " (C) Enclave Hellfire Power Armor Helmet",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/fallout_alaska/alaska_playermodels/enclave_colonel_helmet.mdl",
        ["female"] = "models/fallout_alaska/alaska_playermodels/enclave_colonel_helmet.mdl",
        ["speedboost"] = 0,
        ["HeadDR"] = 7,
        ["training"] = true,
        ["price"] = 0,
        ["weight"] = 1,
        ["slot"] = "helmet",
        ["flag"] = {HIDE_FACIAL_HAIR, HIDE_HAIR, FLAG_HIDE_HEAD},
    },
    ["enclaveRhinopowerarmor"] = {
        ["name"] = " (C) Enclave Rhino Power Armor ",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/nikout/fallout/hellfirearmornpc_body.mdl",
        ["female"] = "models/nikout/fallout/hellfirearmornpc_body.mdl",
        ["speedboost"] = -5,
        ["BodyDR"] = 48,
        ["training"] = true,
        ["price"] = 0,
        ["weight"] = 1,
        ["slot"] = "torso",
        ["flag"] = {HIDE_PANTS, HIDE_BODY, HIDE_HANDS},
    },
    ["enclaveRhinopowerarmorhelmet"] = {
        ["name"] = " (C) Enclave Rhino Power Armor Helmet",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/nikout/fallout/hellfirearmornpc_helmet.mdl",
        ["female"] = "models/nikout/fallout/hellfirearmornpc_helmet.mdl",
        ["speedboost"] = 0,
        ["HeadDR"] = 7,
        ["training"] = true,
        ["price"] = 0,
        ["weight"] = 1,
        ["slot"] = "helmet",
        ["flag"] = {HIDE_FACIAL_HAIR, HIDE_HAIR, FLAG_HIDE_HEAD},
    },
    ["enclavet51powerarmor"] = {
        ["name"] = " (C) Enclave T-51 Power Armor",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/fallout_alaska/alaska_playermodels/t51enclave_body.mdl",
        ["female"] = "models/fallout_alaska/alaska_playermodels/t51enclave_body.mdl",
        ["speedboost"] = -5,
        ["BodyDR"] = 51,
        ["training"] = true,
        ["price"] = 0,
        ["weight"] = 1,
        ["slot"] = "torso",
        ["flag"] = {HIDE_PANTS, HIDE_BODY, HIDE_HANDS},
    },
    ["enclavet51powerarmorhelmet"] = {
        ["name"] = " (C) Enclave T-51 Power Armor Helmet",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/fallout_alaska/alaska_playermodels/t51enclave_helmet.mdl",
        ["female"] = "models/fallout_alaska/alaska_playermodels/t51enclave_helmet.mdl",
        ["speedboost"] = 0,
        ["HeadDR"] = 7,
        ["training"] = true,
        ["price"] = 0,
        ["weight"] = 1,
        ["slot"] = "helmet",
        ["flag"] = {HIDE_FACIAL_HAIR, HIDE_HAIR, FLAG_HIDE_HEAD},
    },
    ["enclavescientist"] = {
        ["name"] = " (C) Enclave Scientist",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/yates/enclave/scientist.mdl",
        ["female"] = "models/yates/enclave/scientist.mdl",
        ["speedboost"] = 0,
        ["BodyDR"] = 50,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 1,
        ["slot"] = "torso",
        ["flag"] = {HIDE_FACIAL_HAIR, HIDE_HAIR, HIDE_PANTS, HIDE_BODY, HIDE_HANDS},
    },
    ["enclaveagentapa"] = {
        ["name"] = " (C) Enclave Agent APA",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/fallout_alaska/alaska_playermodels/apaarmor1_body.mdl",
        ["female"] = "models/fallout_alaska/alaska_playermodels/apaarmor1_body.mdl",
        ["speedboost"] = -2,
        ["BodyDR"] = 65,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 25,
        ["slot"] = "torso",
        ["flag"] = {HIDE_PANTS, HIDE_BODY, HIDE_HANDS},
    },
    ["enclaveagentapahelmet"] = {
        ["name"] = " (C) Enclave Agent APA Helmet",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/fallout_alaska/alaska_playermodels/apaarmor1_helmet.mdl",
        ["female"] = "models/fallout_alaska/alaska_playermodels/apaarmor1_helmet.mdl",
        ["speedboost"] = 0,
        ["HeadDR"] = 10,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 1,
        ["slot"] = "helmet",
        ["flag"] = {HIDE_FACIAL_HAIR, HIDE_HAIR, FLAG_HIDE_HEAD},
    },
    ["EnclaveColonelUniform"] = {
        ["name"] = " (C) Enclave Colonel Uniform",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/thespireroleplay/humans/group522/male.mdl",
        ["female"] = "models/thespireroleplay/humans/group522/female.mdl",
        ["speedboost"] = 4,
        ["BodyDR"] = 55,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 15,
        ["slot"] = "torso",
        ["flag"] = {HIDE_PANTS, HIDE_BODY, HIDE_HANDS},
    },
    --FRONTIERSMAN
    ["riotgear"] = {
        ["name"] = " (C) Riot Gear",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/fallout_alaska/alaska_playermodels/riotsoldier.mdl",
        ["female"] = "models/fallout_alaska/alaska_playermodels/riotsoldier.mdl",
        ["speedboost"] = 5,
        ["BodyDR"] = 50,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 1,
        ["slot"] = "torso",
        ["flag"] = {HIDE_PANTS, HIDE_BODY, HIDE_HANDS},
    },
    ["riotadvancedgear"] = {
        ["name"] = " (C) Riot Advanced Gear",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/fallout_alaska/alaska_playermodels/riotsoldierp2.mdl",
        ["female"] = "models/fallout_alaska/alaska_playermodels/riotsoldierp2.mdl",
        ["speedboost"] = 5,
        ["BodyDR"] = 60,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 1,
        ["slot"] = "torso",
        ["flag"] = {HIDE_PANTS, HIDE_BODY, HIDE_HANDS},
    },
    ["riotelitegear"] = {
        ["name"] = " (C) Riot Elite Gear",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/fallout_alaska/alaska_playermodels/riotsoldierp3.mdl",
        ["female"] = "models/fallout_alaska/alaska_playermodels/riotsoldierp3.mdl",
        ["speedboost"] = 5,
        ["BodyDR"] = 65,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 1,
        ["slot"] = "torso",
        ["flag"] = {HIDE_PANTS, HIDE_BODY, HIDE_HANDS},
    },
    ["riotgearhelmet"] = {
        ["name"] = " (C) Riot Gear Helmet",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/fallout_alaska/alaska_playermodels/riotsoldier_helmet.mdl",
        ["female"] = "models/fallout_alaska/alaska_playermodels/riotsoldier_helmet.mdl",
        ["speedboost"] = 5,
        ["HeadDR"] = 10,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 1,
        ["slot"] = "helmet",
        ["flag"] = {HIDE_FACIAL_HAIR, HIDE_HAIR, FLAG_HIDE_HEAD},
    },
    ["riotAdvnacedhelmet"] = {
        ["name"] = " (C) Riot Advanced Helmet",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/fallout_alaska/alaska_playermodels/riotsoldierp2_helmet.mdl",
        ["female"] = "models/fallout_alaska/alaska_playermodels/riotsoldierp2_helmet.mdl",
        ["speedboost"] = 5,
        ["HeadDR"] = 10,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 1,
        ["slot"] = "helmet",
        ["flag"] = {HIDE_FACIAL_HAIR, HIDE_HAIR, FLAG_HIDE_HEAD},
    },
    ["riotElitehelmet"] = {
        ["name"] = " (C) Riot Elite Helmet",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/fallout_alaska/alaska_playermodels/riotsoldierp3_helmet.mdl",
        ["female"] = "mmodels/fallout_alaska/alaska_playermodels/riotsoldierp3_helmet.mdl",
        ["speedboost"] = 5,
        ["HeadDR"] = 10,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 1,
        ["slot"] = "helmet",
        ["flag"] = {HIDE_FACIAL_HAIR, HIDE_HAIR, FLAG_HIDE_HEAD},
    },
    ["riotenlisted"] = {
        ["name"] = " (C) Riot Enlisted",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/thespireroleplay/humans/group511/male.mdl",
        ["female"] = "models/thespireroleplay/humans/group511/female.mdl",
        ["speedboost"] = 5,
        ["BodyDR"] = 45,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 25,
        ["slot"] = "torso",
        ["flag"] = {HIDE_PANTS, FLAG_HIDE_CHEST, FLAG_HIDE_TORSO},
    },
    ["riotscout"] = {
        ["name"] = " (C) Riot Scout",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/thespireroleplay/humans/group210/male.mdl",
        ["female"] = "models/thespireroleplay/humans/group210/female.mdl",
        ["speedboost"] = 8,
        ["BodyDR"] = 40,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 12,
        ["slot"] = "torso",
        ["flag"] = {HIDE_PANTS, FLAG_HIDE_CHEST, FLAG_HIDE_UPPERARM, FLAG_HIDE_TORSO},
    },
    ["riotscouthelmet"] = {
        ["name"] = " (C) Riot Scout Helmet",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/thespireroleplay/humans/group210/helmet.mdl",
        ["female"] = "models/thespireroleplay/humans/group210/helmetf.mdl",
        ["speedboost"] = 5,
        ["HeadDR"] = 6,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 3,
        ["slot"] = "helmet",
        ["flag"] = {HIDE_HAIR},
    },
    --badlanders
    ["badlandersenlisted"] = {
        ["name"] = " (C) Badlanders Enlisted",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/player/cgcclothing/humans/raidercombat04/male.mdl",
        ["female"] = "models/player/cgcclothing/humans/raidercombat04/female.mdl",
        ["speedboost"] = 9,
        ["BodyDR"] = 43,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 10,
        ["slot"] = "torso",
        ["flag"] = {HIDE_PANTS, HIDE_BODY},
    },
    ["badlandersofficer"] = {
        ["name"] = " (C) Badlanders Officer's Uniform",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/thespireroleplay/humans/group300/male.mdl",
        ["female"] = "models/thespireroleplay/humans/group300/female.mdl",
        ["speedboost"] = 11,
        ["BodyDR"] = 60,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 12,
        ["slot"] = "torso",
        ["flag"] = {HIDE_PANTS, HIDE_BODY, HIDE_HANDS},
    },
    ["badlandersadvancedarmor"] = {
        ["name"] = " (C) Badlanders Advanced Armor",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/player/cgcclothing/humans/raiderdis/male.mdl",
        ["female"] = "models/player/cgcclothing/humans/raiderdis/female.mdl",
        ["speedboost"] = 10,
        ["BodyDR"] = 45,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 1,
        ["slot"] = "torso",
        ["flag"] = {HIDE_PANTS, FLAG_HIDE_CHEST, FLAG_HIDE_UPPERARM, FLAG_HIDE_TORSO},
    },
    ["badlanderspowerarmor"] = {
        ["name"] = " (C) Badlanders Power Armor",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/thespireroleplay/humans/group124/male.mdl",
        ["female"] = "models/thespireroleplay/humans/group124/female.mdl",
        ["speedboost"] = 5,
        ["BodyDR"] = 50,
        ["training"] = true,
        ["price"] = 0,
        ["weight"] = 25,
        ["slot"] = "torso",
        ["flag"] = {HIDE_PANTS, HIDE_BODY, HIDE_HANDS},
    },
    ["badlanderspowerarmorhelmet"] = {
        ["name"] = " (C) Badlanders Power Armor Helmet",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/fallout_alaska/alaska_playermodels/t49powerarmor_helmet.mdl",
        ["female"] = "models/fallout_alaska/alaska_playermodels/t49powerarmor_helmet.mdl",
        ["speedboost"] = 5,
        ["HeadDR"] = 49,
        ["training"] = true,
        ["price"] = 0,
        ["weight"] = 1,
        ["slot"] = "helmet",
        ["flag"] = {HIDE_FACIAL_HAIR, HIDE_HAIR, FLAG_HIDE_HEAD},
    },
    ["badlanderscagedpowerarmor"] = {
        ["name"] = " (C) Badlanders Caged Power Armor",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/player/cgcclothing/humans/powerarmor_raider/powerarmor_raider.mdl",
        ["female"] = "models/player/cgcclothing/humans/powerarmor_raider/powerarmor_raider.mdl",
        ["speedboost"] = 5,
        ["BodyDR"] = 45,
        ["training"] = true,
        ["price"] = 0,
        ["weight"] = 1,
        ["slot"] = "torso",
        ["flag"] = {HIDE_PANTS, HIDE_BODY},
    },
    ["badlanderscagedpowerarmorhelmet"] = {
        ["name"] = " (C) Badlanders Caged Power Armor Helmet",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/player/cgcclothing/humans/powerarmor_raider/powerarmor_raider_helmet.mdl",
        ["female"] = "models/player/cgcclothing/humans/powerarmor_raider/powerarmor_raider_helmet.mdl",
        ["speedboost"] = 5,
        ["HeadDR"] = 8,
        ["training"] = true,
        ["price"] = 0,
        ["weight"] = 1,
        ["slot"] = "helmet",
        ["flag"] = {HIDE_FACIAL_HAIR, HIDE_HAIR, FLAG_HIDE_HEAD},
    },
    ["badlandersrangehelmet"] = {
        ["name"] = " (C) Badlander's Scavenged Ranger Helmet",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/fallout_alaska/alaska_playermodels/roadfighter_helmet.mdl",
        ["female"] = "models/fallout_alaska/alaska_playermodels/roadfighter_helmet.mdl",
        ["speedboost"] = 5,
        ["HeadDR"] = 7,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 4,
        ["slot"] = "helmet",
        ["flag"] = {HIDE_HAIR, HIDE_FACIAL_HAIR, FLAG_HIDE_HEAD},
    },
    ["badlandersbikerhelmet"] = {
        ["name"] = " (C) Badlander's Scavenged Biker Helmet",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/player/cgcclothing/humans/raiderdis/helmet.mdl",
        ["female"] = "models/player/cgcclothing/humans/raiderdis/helmetf.mdl",
        ["speedboost"] = 5,
        ["HeadDR"] = 6,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 3,
        ["slot"] = "helmet",
        ["flag"] = {HIDE_HAIR, HIDE_FACIAL_HAIR, FLAG_HIDE_HEAD},
    },
    ["badlandershood"] = {
        ["name"] = " (C) Badlander's Hood",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/fallout_alaska/headgear/helmet_m_raiderhood.mdl",
        ["female"] = "models/fallout_alaska/headgear/helmet_f_raiderhood.mdl",
        ["speedboost"] = 5,
        ["HeadDR"] = 5,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 2,
        ["slot"] = "helmet",
        ["flag"] = {HIDE_HAIR, FLAG_HIDE_HEAD, HIDE_FACIAL_HAIR},
    },
    ["badlandersscoutarmor"] = {
        ["name"] = " (C) Badlanders Scout Armor",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/thespireroleplay/humans/group316/male.mdl",
        ["female"] = "models/thespireroleplay/humans/group316/female.mdl",
        ["speedboost"] = 11,
        ["BodyDR"] = 39,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 8,
        ["slot"] = "torso",
        ["flag"] = {HIDE_PANTS},
    },
    --BOS ARMOR
    ["bost45"] = {
        ["name"] = " (C) BOS t-45",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/player/alaska/bost45/male.mdl",
        ["female"] = "models/player/alaska/bost45/male.mdl",
        ["speedboost"] = -4,
        ["BodyDR"] = 45,
        ["training"] = true,
        ["price"] = 0,
        ["weight"] = 1,
        ["slot"] = "torso",
        ["flag"] = {HIDE_PANTS, HIDE_BODY, HIDE_HANDS},
    },
    ["bost45helmet"] = {
        ["name"] = " (C) BOS t-45 helmet",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/fallout_3/power_armor_admin_helmet.mdl",
        ["female"] = "models/fallout_3/power_armor_admin_helmet.mdl",
        ["speedboost"] = 0,
        ["HeadDR"] = 4,
        ["training"] = true,
        ["price"] = 0,
        ["weight"] = 1,
        ["slot"] = "helmet",
        ["flag"] = {HIDE_HAIR, HIDE_FACIAL_HAIR, FLAG_HIDE_HEAD},
    },
    ["bost51test"] = {
        ["name"] = " (C) BOS t-51",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/thespireroleplay/humans/group215/male.mdl",
        ["female"] = "models/thespireroleplay/humans/group215/female.mdl",
        ["speedboost"] = -5,
        ["BodyDR"] = 51,
        ["training"] = true,
        ["price"] = 0,
        ["weight"] = 25,
        ["slot"] = "torso",
        ["flag"] = {HIDE_PANTS, HIDE_BODY, HIDE_HANDS},
    },
    ["bost51helmettest"] = {
        ["name"] = " (C) BOS t-51 helmet",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/thespireroleplay/humans/group215/helmet.mdl",
        ["female"] = "models/thespireroleplay/humans/group215/helmet.mdl",
        ["speedboost"] = 0,
        ["HeadDR"] = 5,
        ["training"] = true,
        ["price"] = 0,
        ["weight"] = 5,
        ["slot"] = "helmet",
        ["flag"] = {HIDE_HAIR, HIDE_FACIAL_HAIR, FLAG_HIDE_HEAD},
    },
    ["bosX01"] = {
        ["name"] = " (C) BOS X-01",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/alaska/bosapa/body.mdl",
        ["female"] = "models/alaska/bosapa/body.mdl",
        ["speedboost"] = -6,
        ["BodyDR"] = 65,
        ["training"] = true,
        ["price"] = 0,
        ["weight"] = 25,
        ["slot"] = "torso",
        ["flag"] = {HIDE_PANTS, HIDE_BODY},
    },
    ["bosX01MKll"] = {
        ["name"] = " (C) BOS X-01 MKll",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/player/alaska/bosapa/body.mdl",
        ["female"] = "models/player/alaska/bosapa/body.mdl",
        ["speedboost"] = -6,
        ["BodyDR"] = 65,
        ["training"] = true,
        ["price"] = 0,
        ["weight"] = 1,
        ["slot"] = "torso",
        ["flag"] = {HIDE_PANTS, HIDE_BODY},
    },
    ["bosX01helmetMKll"] = {
        ["name"] = " (C) BOS X-01 Helmet MKll",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/player/alaska/bosapa/helmet.mdl",
        ["female"] = "models/player/alaska/bosapa/helmet.mdl",
        ["speedboost"] = 0,
        ["HeadDR"] = 10,
        ["training"] = true,
        ["price"] = 0,
        ["weight"] = 5,
        ["slot"] = "helmet",
        ["flag"] = {HIDE_HAIR, HIDE_FACIAL_HAIR, FLAG_HIDE_HEAD},
    },
    ["bosX01helmet"] = {
        ["name"] = " (C) BOS X-01 Helmet",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/alaska/bosapa/helmet.mdl",
        ["female"] = "models/alaska/bosapa/helmet.mdl",
        ["speedboost"] = 0,
        ["HeadDR"] = 10,
        ["training"] = true,
        ["price"] = 0,
        ["weight"] = 5,
        ["slot"] = "helmet",
        ["flag"] = {HIDE_HAIR, HIDE_FACIAL_HAIR, FLAG_HIDE_HEAD},
    },
    ["BOSLegendaryPaladinPowerArmor"] = {
        ["name"] = " (C) BOS Legendary Paladin Power Armor",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/fallout_alaska/alaska_playermodels/advancedmidwest_paladin_body.mdl",
        ["female"] = "models/fallout_alaska/alaska_playermodels/advancedmidwest_paladin_body.mdl",
        ["speedboost"] = -7,
        ["BodyDR"] = 65,
        ["training"] = true,
        ["price"] = 0,
        ["weight"] = 1,
        ["slot"] = "torso",
        ["flag"] = {HIDE_PANTS, HIDE_BODY, HIDE_HANDS},
    },
    ["BOSLegendaryPaladinhelmet"] = {
        ["name"] = " (C) BOS Legendary Paladin hemlet",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/fallout_alaska/alaska_playermodels/advancedmidwest_paladin_helmet.mdl",
        ["female"] = "mmodels/fallout_alaska/alaska_playermodels/advancedmidwest_paladin_helmet.mdl",
        ["speedboost"] = 0,
        ["HeadDR"] = 10,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 5,
        ["slot"] = "helmet",
        ["flag"] = {HIDE_HAIR, HIDE_FACIAL_HAIR, FLAG_HIDE_HEAD},
    },
    ["BOSadvancedPaladinPowerArmor"] = {
        ["name"] = " (C) BOS Advanced Paladin Power Armor",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/fallout_alaska/alaska_playermodels/wintermidwest_powerarmor_body.mdl",
        ["female"] = "models/fallout_alaska/alaska_playermodels/wintermidwest_powerarmor_body.mdl",
        ["speedboost"] = -6,
        ["BodyDR"] = 55,
        ["training"] = true,
        ["price"] = 0,
        ["weight"] = 1,
        ["slot"] = "torso",
        ["flag"] = {HIDE_PANTS, HIDE_BODY, HIDE_HANDS},
    },
    ["BOSadvancedPaladinhelmet"] = {
        ["name"] = " (C) BOS Advanced Paladin Helmet",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/fallout_alaska/alaska_playermodels/wintermidwest_powerarmor_helmet.mdl",
        ["female"] = "models/fallout_alaska/alaska_playermodels/wintermidwest_powerarmor_helmet.mdl",
        ["speedboost"] = 0,
        ["HeadDR"] = 7,
        ["training"] = true,
        ["price"] = 0,
        ["weight"] = 1,
        ["slot"] = "helmet",
        ["flag"] = {HIDE_HAIR, HIDE_FACIAL_HAIR, FLAG_HIDE_HEAD},
    },
    ["BOSenlistedarmor"] = {
        ["name"] = " (C) BOS Enlisted Armor",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/fallout_alaska/humans/reconarmor/recon_male_body.mdl",
        ["female"] = "models/fallout_alaska/humans/reconarmor/recon_female_body.mdl",
        ["speedboost"] = 6,
        ["BodyDR"] = 35,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 5,
        ["slot"] = "torso",
        ["flag"] = {HIDE_PANTS, HIDE_BODY},
    },
    ["BOSenlistedhood"] = {
        ["name"] = " (C) BOS Enlisted hood",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/fallout_alaska/humans/reconarmor/recon_male_helmet.mdl",
        ["female"] = "models/fallout_alaska/humans/reconarmor/recon_female_helmet.mdl",
        ["speedboost"] = 0,
        ["HeadDR"] = 4,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 1,
        ["slot"] = "helmet",
        ["flag"] = {HIDE_HAIR},
    },
    ["BOSreconarmor"] = {
        ["name"] = " (C) BOS Scribe Armor",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/thespireroleplay/humans/group102/male.mdl",
        ["female"] = "models/thespireroleplay/humans/group102/female.mdl",
        ["speedboost"] = 7,
        ["BodyDR"] = 35,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 1,
        ["slot"] = "torso",
        ["flag"] = {HIDE_PANTS, HIDE_BODY},
    },
    --Militia Armor
    ["AlaskanExile"] = {
        ["name"] = " (C) Alaskan Exile",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/ncr/exilem.mdl",
        ["female"] = "models/ncr/exilef.mdl",
        ["speedboost"] = 12,
        ["BodyDR"] = 40,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 1,
        ["slot"] = "torso",
        ["flag"] = {HIDE_PANTS, HIDE_BODY},
    },
    ["Alaskancolonelhelmet"] = {
        ["name"] = " (C) Alaskan Colonel Helmet",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/player/cgcclothing/humans/militia_courier/militia_riot_helmet.mdl",
        ["female"] = "models/player/cgcclothing/humans/militia_courier/militia_riot_helmet.mdl",
        ["speedboost"] = 12,
        ["HeadDR"] = 10,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 1,
        ["slot"] = "helmet",
        ["flag"] = {HIDE_HAIR, HIDE_FACIAL_HAIR, FLAG_HIDE_HEAD},
    },
    ["Alaskancolonel"] = {
        ["name"] = " (C) Alaskan Colonel",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/ncr/colonelm.mdl",
        ["female"] = "models/ncr/colonelf.mdl",
        ["speedboost"] = 17,
        ["BodyDR"] = 65,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 1,
        ["slot"] = "torso",
        ["flag"] = {HIDE_PANTS, HIDE_BODY, FLAG_HIDE_CHEST},
    },
    ["Alaskanmilitiaofficer"] = {
        ["name"] = " (C) Alaskan Militia Officer",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/ncr/parkam.mdl",
        ["female"] = "models/ncr/parkaf.mdl",
        ["speedboost"] = 16,
        ["BodyDR"] = 55,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 1,
        ["slot"] = "torso",
        ["flag"] = {HIDE_PANTS, HIDE_BODY},
    },
    ["Alaskanmilitiapatrollranger"] = {
        ["name"] = " (C) Alaskan Militia Patrol Ranger",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/ncr/patrolm.mdl",
        ["female"] = "models/ncr/patrolf.mdl",
        ["speedboost"] = 16,
        ["BodyDR"] = 50,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 1,
        ["slot"] = "torso",
        ["flag"] = {HIDE_PANTS, HIDE_BODY},
    },
    ["AlaskanVeteranRangerUniform"] = {
        ["name"] = " (C) Alaskan Veteran Ranger Uniform",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/ncr/snowrangerm.mdl",
        ["female"] = "models/ncr/snowrangerf.mdl",
        ["speedboost"] = 10,
        ["BodyDR"] = 65,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 15,
        ["slot"] = "torso",
        ["flag"] = {HIDE_PANTS, HIDE_BODY},
    },
    ["AlaskanRangerUniform"] = {
        ["name"] = " (C) Alaskan Ranger Uniform",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/fallout_alaska/alaska_playermodels/alaska_ranger_body.mdl",
        ["female"] = "models/fallout_alaska/alaska_playermodels/alaska_ranger_body.mdl",
        ["speedboost"] = 19,
        ["BodyDR"] = 55,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 25,
        ["slot"] = "torso",
        ["flag"] = {HIDE_PANTS, HIDE_BODY, HIDE_HANDS},
    },
    ["AlaskanRangerHelmet"] = {
        ["name"] = " (C) Alaskan Ranger Helmet",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/fallout_alaska/alaska_playermodels/alaska_ranger_helmet.mdl",
        ["female"] = "models/fallout_alaska/alaska_playermodels/alaska_ranger_helmet.mdl",
        ["speedboost"] = 6,
        ["HeadDR"] = 8,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 1,
        ["slot"] = "helmet",
        ["flag"] = {HIDE_HAIR, HIDE_FACIAL_HAIR, FLAG_HIDE_HEAD},
    },
    ["AlaskanRangerscout"] = {
        ["name"] = " (C) Alaskan Scout Uniform",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/player/cgcclothing/humans/reconsniper/male.mdl",
        ["female"] = "models/player/cgcclothing/humans/reconsniper/male.mdl",
        ["speedboost"] = 18,
        ["BodyDR"] = 51,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 15,
        ["slot"] = "torso",
        ["flag"] = {HIDE_PANTS, HIDE_BODY},
    },
    --institute Armors
    ["Attackstrigade"] = {
        ["name"] = " (C) Institute Attack Strigade",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/player/alaska/strigidae.mdl",
        ["female"] = "models/player/alaska/strigidae.mdl",
        ["speedboost"] = 0,
        ["BodyDR"] = 79,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 1,
        ["slot"] = "torso",
        ["flag"] = {HIDE_HAIR, HIDE_FACIAL_HAIR, HIDE_PANTS, HIDE_BODY, HIDE_HANDS, HIDE_HEAD},
    },
    ["tankstrigade"] = {
        ["name"] = " (C) Institute Tank Strigade",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/player/alaska/strigidae.mdl",
        ["female"] = "models/player/alaska/strigidae.mdl",
        ["speedboost"] = 0,
        ["BodyDR"] = 79,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 1,
        ["slot"] = "torso",
        ["flag"] = {HIDE_PANTS, HIDE_BODY, HIDE_HANDS, HIDE_HAIR, HIDE_FACIAL_HAIR, HIDE_HEAD},
    },
    ["powerstrigade"] = {
        ["name"] = " (C) Institute Power Strigade",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/models/adi/institute/powerarmor_institute.mdl",
        ["female"] = "models/models/adi/institute/powerarmor_institute.mdl",
        ["speedboost"] = 0,
        ["BodyDR"] = 79,
        ["training"] = true,
        ["price"] = 0,
        ["weight"] = 1,
        ["slot"] = "torso",
        ["flag"] = {HIDE_PANTS, HIDE_BODY, HIDE_HANDS, HIDE_HAIR, HIDE_FACIAL_HAIR, HIDE_HEAD},
    },
    ["Generation01Synth"] = {
        ["name"] = " (C) Institute Generation 01 Synth",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/nutscript/player/alaska/robotrace.mdl",
        ["female"] = "models/nutscript/player/alaska/robotrace.mdl",
        ["speedboost"] = 0,
        ["BodyDR"] = 0,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 1,
        ["slot"] = "Model",
        ["flag"] = {HIDE_PANTS, HIDE_BODY, HIDE_HANDS, HIDE_HAIR, HIDE_FACIAL_HAIR, HIDE_HEAD},
    },
    ["Generation02Synth"] = {
        ["name"] = " (C)  Institute Generation 02 Synth",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/synthgen2.mdl",
        ["female"] = "models/synthgen2.mdl",
        ["speedboost"] = 0,
        ["BodyDR"] = 79,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 1,
        ["slot"] = "Model",
        ["flag"] = {HIDE_PANTS, HIDE_BODY, HIDE_HANDS, HIDE_HAIR, HIDE_FACIAL_HAIR, HIDE_HEAD},
    },
    ["Generation01Synth1"] = {
        ["name"] = " (C) Institute Generation 01 Synth",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/arachnit/fallout4/synths/synthgeneration1_pm.mdl",
        ["female"] = "models/arachnit/fallout4/synths/synthgeneration1_pm.mdl",
        ["speedboost"] = 0,
        ["BodyDR"] = 0,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 1,
        ["slot"] = "Model",
        ["flag"] = {HIDE_PANTS, HIDE_BODY, HIDE_HANDS, HIDE_HAIR, HIDE_FACIAL_HAIR, HIDE_HEAD},
    },
    --Guild
    ["Blizzardcompanyenlisted"] = {
        ["name"] = " (C) Blizzard Company Enlisted",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/thespireroleplay/humans/group002/male.mdl",
        ["female"] = "models/thespireroleplay/humans/group002/female.mdl",
        ["speedboost"] = 8,
        ["BodyDR"] = 45,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 1,
        ["slot"] = "torso",
        ["flag"] = {HIDE_PANTS, FLAG_HIDE_CHEST, FLAG_HIDE_UPPERARM, FLAG_HIDE_TORSO},
    },
    ["Blizzardcompanyhuntsman"] = {
        ["name"] = " (C) Blizzard Company Hunter Uniform",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/alaska/bountyhunters/manhunter.mdl",
        ["female"] = "models/alaska/bountyhunters/manhunter.mdl",
        ["speedboost"] = 9,
        ["BodyDR"] = 55,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 1,
        ["slot"] = "torso",
        ["flag"] = {HIDE_PANTS, HIDE_BODY},
    },
    ["Blizzardcompanyhuntsmanwinter"] = {
        ["name"] = " (C) Blizzard Company Hunter Uniform winterized",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/alaska/bountyhunters/manhunter_winterized.mdl",
        ["female"] = "models/alaska/bountyhunters/manhunter_winterized.mdl",
        ["speedboost"] = 10,
        ["BodyDR"] = 55,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 11,
        ["slot"] = "torso",
        ["flag"] = {HIDE_PANTS, HIDE_BODY},
    },
    ["bsharpsarmor"] = {
        ["name"] = " (C) Scavenged Cybernetic",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/bsharps/roboticarm/body.mdl",
        ["female"] = "models/bsharps/roboticarm/body.mdl",
        ["speedboost"] = 11,
        ["BodyDR"] = 65,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 16,
        ["slot"] = "torso",
        ["flag"] = {HIDE_PANTS, HIDE_BODY, HIDE_HANDS},
    },
    ["bsharpsarmorhelmet"] = {
        ["name"] = " (C) Scavenged Cybernetic Helmet",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/bsharps/roboticarm/helmet.mdl",
        ["female"] = "models/bsharps/roboticarm/helmet.mdl",
        ["speedboost"] = 0,
        ["HeadDR"] = 30,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 5,
        ["slot"] = "Helmet",
        ["flag"] = {HIDE_HAIR, HIDE_FACIAL_HAIR, HIDE_HEAD},
    },
    --gunner
    ["Gunnerairforce"] = {
        ["name"] = " (C) Gunner Airforce Power Armor",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/adi/falllout/airforcepa.mdl",
        ["female"] = "models/adi/falllout/airforcepa.mdl",
        ["speedboost"] = 0,
        ["BodyDR"] = 50,
        ["HeadDR"] = 5,
        ["training"] = true,
        ["price"] = 0,
        ["weight"] = 1,
        ["slot"] = "torso",
        ["flag"] = {HIDE_HAIR, HIDE_PANTS, HIDE_BODY, HIDE_HANDS, HIDE_FACIAL_HAIR, HIDE_HAIR, HIDE_HEAD},
    },
    ["Gunnersamuriarmor"] = {
        ["name"] = " (C) Gunner Samuri Armor",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/player/alaska/wstlndsamurai.mdl",
        ["female"] = "models/player/alaska/wstlndsamurai.mdl",
        ["speedboost"] = 0,
        ["BodyDR"] = 49,
        ["HeadDR"] = 4,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 25,
        ["slot"] = "torso",
        ["flag"] = {HIDE_HAIR, HIDE_PANTS, HIDE_BODY, HIDE_HANDS, HIDE_FACIAL_HAIR, HIDE_HAIR, HIDE_HEAD},
    },
    ["GunnerBrigadierArmor"] = {
        ["name"] = " (C) Gunner Brigadier Armor",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/player/alaska/themerc.mdl",
        ["female"] = "models/player/alaska/themerc.mdl",
        ["speedboost"] = 0,
        ["BodyDR"] = 48,
        ["HeadDR"] = 7,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 25,
        ["slot"] = "torso",
        ["flag"] = {HIDE_HAIR, HIDE_PANTS, HIDE_BODY, HIDE_HANDS, HIDE_FACIAL_HAIR, HIDE_HAIR, HIDE_HEAD},
    },
    ["Gunnerenlisted"] = {
        ["name"] = " (C) Gunner Enlisted",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/player/alaska/advcombat.mdl",
        ["female"] = "models/player/alaska/advcombat.mdl",
        ["speedboost"] = 0,
        ["BodyDR"] = 40,
        ["HeadDR"] = 4,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 25,
        ["slot"] = "torso",
        ["flag"] = {HIDE_HAIR, HIDE_PANTS, HIDE_BODY, HIDE_HANDS, HIDE_FACIAL_HAIR, HIDE_HAIR, HIDE_HEAD},
    },
    ["GunnerRDUniform"] = {
        ["name"] = " (C) Gunner R&D Uniform",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/player/alaska/gunrecon.mdl",
        ["female"] = "models/player/alaska/gunrecon.mdl",
        ["speedboost"] = 0,
        ["BodyDR"] = 35,
        ["HeadDR"] = 3,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 1,
        ["slot"] = "torso",
        ["flag"] = {HIDE_HAIR, HIDE_PANTS, HIDE_BODY, HIDE_HANDS, HIDE_FACIAL_HAIR, HIDE_HAIR, HIDE_HEAD},
    },
    ["GunnerPowerArmor"] = {
        ["name"] = " (C) Gunner Power Armor",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/adi/falllout/airforcepa.mdl",
        ["female"] = "models/adi/falllout/airforcepa.mdl",
        ["speedboost"] = 0,
        ["BodyDR"] = 45,
        ["HeadDR"] = 6,
        ["training"] = true,
        ["price"] = 0,
        ["weight"] = 25,
        ["slot"] = "torso",
        ["flag"] = {HIDE_HAIR, HIDE_PANTS, HIDE_BODY, HIDE_HANDS, HIDE_FACIAL_HAIR, HIDE_HAIR, HIDE_HEAD},
    },
    ["GunnerSupremeCommanderArmor"] = {
        ["name"] = " (C) Gunner Supreme Commander Armor",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/player/alaska/t60gunner.mdl",
        ["female"] = "models/player/alaska/t60gunner.mdl",
        ["speedboost"] = 0,
        ["BodyDR"] = 65,
        ["HeadDR"] = 8,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 1,
        ["slot"] = "torso",
        ["flag"] = {HIDE_HAIR, HIDE_PANTS, HIDE_BODY, HIDE_HANDS, HIDE_FACIAL_HAIR, HIDE_HAIR, HIDE_HEAD},
    },
    ["baratabody"] = {
        ["name"] = "Rata's Armor",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/fallout_alaska/alaska_playermodels/apatesla1_body.mdl",
        ["female"] = "models/fallout_alaska/alaska_playermodels/apatesla1_body.mdl",
        ["speedboost"] = 0,
        ["BodyDR"] = 50,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 1,
        ["slot"] = "torso",
        ["flag"] = {HIDE_PANTS, HIDE_BODY, HIDE_HANDS},
    },
    ["baratahead"] = {
        ["name"] = "Rata's Helmet",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/fallout_alaska/headgear/helmet_m_apamk2.mdl",
        ["female"] = "models/fallout_alaska/headgear/helmet_m_apamk2.mdl",
        ["speedboost"] = 0,
        ["HeadDR"] = 5,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 1,
        ["slot"] = "helmet",
        ["flag"] = {HIDE_FACIAL_HAIR, HIDE_HAIR, FLAG_HIDE_HEAD},
    },
    --event 
    ["Alien"] = {
        ["name"] = " (C) Alien",
        ["model"] = "models/thespireroleplay/items/clothes/group002.mdl",
        ["male"] = "models/f3alien/slow.mdl",
        ["female"] = "models/f3alien/slow.mdl",
        ["speedboost"] = 0,
        ["BodyDR"] = 95,
        ["training"] = false,
        ["price"] = 0,
        ["weight"] = 1,
        ["slot"] = "model",
        ["flag"] = {HIDE_PANTS, HIDE_BODY, HIDE_HANDS, HIDE_HAIR, HIDE_FACIAL_HAIR, HIDE_HEAD},
    },
}

----- END OF ARMOR DEFINE
print("REE")
--models/player/cgcclothing/humans/powerarmor_raider/powerarmor_raider.mdl
local playerMT = FindMetaTable("Player")

function playerMT:CalculateStats()
    local char = self:getChar()
    if char == nil then return end

    local newAttribsBoost = {
        str = 0,
        per = 0,
        ["end"] = 0,
        cha = 0,
        int = 0,
        agi = 0,
        luc = 0,
    }

    local allEquipedItems = {}

    for i, v in pairs(char:getInv().items) do
        if v:getData("equip") then
            for _, attr in pairs(v.attrib or {}) do
                newAttribsBoost[_] = newAttribsBoost[_] + attr
            end
        end
    end

    timer.Simple(1, function()
        local currentHPPercentage = self:Health() / self:GetMaxHealth()
        local newMaxHP = 100 + (char:getAttrib("end") * 25)
        self:SetMaxHealth(newMaxHP)
        self:SetHealth(newMaxHP * currentHPPercentage)
    end)

    for i, v in pairs(newAttribsBoost) do
        char:addBoost("equip", i, v)
    end

    local baseWeight = 135
    baseWeight = baseWeight + (char:getData("backpackslots", 0) * 10)
    local WeightPerStr = 15
    local multiplierCarry = 1
    
    if char:getData("VIP") == 1 then
        multiplierCarry = multiplierCarry * 2
    end

    char:getInv():setData("maxWeight", (baseWeight + (WeightPerStr * char:getAttrib("str"))) * multiplierCarry)
end

function DISPLAY_ARMOR_STATS(self)
    local build = {
        {1, "Damage Reduction: " .. self.resisbody .. "%"},
        {-1, ""},
        {-1, "- Current Stats -"}
    }

    -- PrintTable(nut.attribs.list)
    --
    -- for i, v in pairs(self.attrib or {}) do
    --     build[#build + 1] = {1, nut.attribs.list[i].name .. ": " .. (v > 0 and "+" or "") .. v}
    -- end
    local newAttribsBoost = {"str", "per", "end", "cha", "int", "agi", "luc"}

    local char = LocalPlayer():getChar()

    for i, v in pairs(newAttribsBoost) do
        local difference = 0

        if self:getData("equip") then
            difference = 0
        end

        difference = self.attrib[v] or 0
        local clearDiff = true

        -- get item with same slot
        for _, item in pairs(char:getInv():getItems()) do
            if item:getData("equip", false) == true and item.slot == self.slot and item:getID() ~= self:getID() then
                if clearDiff then
                    difference = 0
                    clearDiff = false
                end

                item.attrib = item.attrib or {}
                difference = difference - (item.attrib[v] or 0)
            end
        end

        if difference < 0 then
            build[#build + 1] = {1, nut.attribs.list[v].name .. ": " .. char:getAttrib(v), Color(255, 0, 0), difference}
        else
            build[#build + 1] = {1, nut.attribs.list[v].name .. ": " .. char:getAttrib(v), Color(25, 255, 25), difference == 0 and "" or ("+" .. difference)}
        end
    end

    return build
end

function YSHERA_ADD_ARMOR(ID, table)
    ID = ID:lower()
    local ITEM = nut.item.list[ID] or nut.item.register(ID, "base_armor", nil, nil, true)

    local v = {
        name = table.name,
        desc = "null",
        model = table.model,
        male = table.male,
        female = table.female,
        weight = table.weight or 1,
        type = "armor",
        armor = 100,
        dr = math.max(table.HeadDR or 0, table.BodyDR or 0),
        --armorType = "powerarmor",
        slot = table.slot or "Torso",
        price = table.price or 0,
        flag = table.flag    or {HIDE_PANTS, HIDE_BODY, HIDE_HANDS},
        attribs = table.attribs or {},
    }

    ITEM.name = v["name"]
    ITEM.model = v["model"] or "models/hunter/blocks/cube025x025x025.mdl"
    ITEM.isPA = v["training"] or false
    ITEM.type = v["type"]
    ITEM.price = v["price"] or 0
    ITEM.female = v["female"] or v.model
    ITEM.male = v["male"] or v.model 
    ITEM.weight = v["weight"] or 5
    ITEM.category = "ARMOR"
    ITEM.resisbody = 0
    ITEM.resishead = 0
    ITEM.skipFlags = v.flag
    ITEM.slot = v["slot"] or "torso"
    ITEM.struct = DISPLAY_ARMOR_STATS
    ITEM.resisbody = v.dr or 0
    ITEM.resishead = 0

    ITEM:hook("use", function(item)
        timer.Simple(1, function()
            item:getOwner():CalculateStats()
        end)
    end)

    ITEM.attrib = v.attribs or {} 

    ITEM.skipFlags = v["flag"] or {HIDE_PANTS, HIDE_HANDS, HIDE_FACIAL_HAIR, HIDE_HAIR, HIDE_BODY, HIDE_TORSO}
    PrintTable(ITEM.skipFlags)
end

hook.Add("PlayerSpawn", "respawn__gigachad", function(ply)
    timer.Simple(1,function() ply:CalculateStats() end)
end)

hook.Add("InitializedPlugins", "ys_armor", function()
    timer.Simple(1, function()
        for i, v in pairs(YSHERA_ARMORS) do
            YSHERA_ADD_ARMOR(i, v)
        end
    end)
end)
 
if nut then
    for i, v in pairs(YSHERA_ARMORS) do
        YSHERA_ADD_ARMOR(i, v)
    end
end

local v = {
    name = "Wastelander Power Armor",
    desc = "A power armor made for wastelander.",
    model = "models/player/cgcclothing/humans/powerarmor_raider/powerarmor_raider.mdl",
    weight = 10,
    type = "armor",
    armor = 100,
    armorType = "powerarmor",
    price = 100,
    slot = "torso",
    maxArmor = 100,
    price = 0,
    flag = {HIDE_PANTS, HIDE_BODY, HIDE_HANDS},
}